### ISSUE TITLE
Error trying to import from SIC 16.1.1

### ISSUE THREAD

**Issue by henhell** [Alezy80/SIC2KeePass#1]
Trying to import a safe in the cloud xml database, and up with the error:
The given key was not present in the dictionary.

For obvious reasons I will not include the xml file :)

If this is because of an error in the xml or an unsupported field, the offending row would be tremendously helpful in the error message.

**Comment by Alezy80** [comment]
Check new version (v1.0.1.0), it has little more robust importing, and if any error were occurred it writes more detailed error message

**Comment by henhell** [comment]
Worked flawlessly with v1.0.1.0, thank you!
