### ISSUE TITLE
Cannot import SIC in Keepass 1.31

### ISSUE THREAD

**Issue by mreich99** [Alezy80/SIC2KeePass#2]
I am trying to use the plugin for Keepass 1.31. I downloaded the file SafeInCloudImp.plgx and put it in the Keepass installation directory. I started Keepass and there is no entry for the plugin in "Tools/Plugins". I went to File import and there are entries e.g. for CSV Files or Keepass Database but no option for Safe in Cloud Database. Am I doing something wrong or maybe do I need another version of Keepass?

**Comment by Alezy80** [comment]
The plugin is **only** for 2.xx version, it is stated on KeePass plugins page and on main page of SIC2KeePass plugin
