### ISSUE TITLE
Does not work with Keepass 2.38

### ISSUE THREAD

**Issue by metaer** [Alezy80/SIC2KeePass#4]
When I start Keepass2 with this plugin - I get such error:

> The following plugin is incompativle with the current KeePass version:
> /usr/lib/keepass2/SafeInCloudImp.plgx
> 
> Have a look at the plugin's website for an appropriate version.

SIC2KeePass 2.0.1.0 https://github.com/Alezy80/SIC2KeePass/releases/tag/v2.0.1.0
Keepass 2.38
Linux Mint 19.1

**Comment by Alezy80** [comment]
@metaer, try to install `mono-complete` package from application manager. It works for me.

**Comment by metaer** [comment]
Now it works. Thank you!
